-- Corrected Properties Table for Real Estate Platform
-- This table matches the application's actual schema and requirements

CREATE TABLE IF NOT EXISTS `properties` (
  `id` int NOT NULL AUTO_INCREMENT,
  `builder_id` int NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `property_type_id` int DEFAULT NULL,
  `price` decimal(15,2) NOT NULL,
  `price_unit` enum('total','per_sqft','per_month') DEFAULT 'total',
  `area_sqft` decimal(10,2) DEFAULT NULL,
  `bedrooms` int DEFAULT NULL,
  `bathrooms` int DEFAULT NULL,
  `parking_spaces` int DEFAULT '0',
  `furnishing` enum('unfurnished','semi-furnished','fully-furnished') DEFAULT NULL,
  `facing` varchar(20) DEFAULT NULL,
  `floor_number` int DEFAULT NULL,
  `total_floors` int DEFAULT NULL,
  `age_of_property` varchar(50) DEFAULT NULL,
  `address_line1` varchar(255) NOT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `city` varchar(100) NOT NULL,
  `state` varchar(100) NOT NULL,
  `pincode` varchar(10) NOT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `status` enum('available','sold','rented','under_construction') DEFAULT 'available',
  `is_visible` tinyint(1) DEFAULT '1',
  `is_featured` tinyint(1) DEFAULT '0',
  `listing_type` enum('sale','rent') DEFAULT 'sale',
  `subscription_plan` enum('premium','elite','super_elite') DEFAULT 'premium',
  `map_address` varchar(500) DEFAULT NULL,
  `google_place_id` varchar(255) DEFAULT NULL,
  `view_count` int NOT NULL DEFAULT '0',
  `contact_count` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `property_type_id` (`property_type_id`),
  KEY `idx_builder` (`builder_id`),
  KEY `idx_city` (`city`),
  KEY `idx_status` (`status`),
  KEY `idx_price` (`price`),
  KEY `idx_listing_type` (`listing_type`),
  FULLTEXT KEY `idx_search` (`title`,`description`,`address_line1`,`city`),
  CONSTRAINT `properties_ibfk_1` FOREIGN KEY (`builder_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `properties_ibfk_2` FOREIGN KEY (`property_type_id`) REFERENCES `property_types` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

